name: raven-hydro Testing Suite

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pip:
    name: Pip with Python${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.9"
            os: ubuntu-latest
          - python-version: "3.10"
            os: macos-latest
          - python-version: "3.10"
            os: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        if: ${{ matrix.os != windows-latest }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install conda with NetCDF4 (Windows)
        if: ${{ matrix.os == 'windows-latest'}}
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          micromamba-version: 'latest'
          extra-specs: |
            python=${{ matrix.python-version }}
            pip
            libnetcdf
      - name: Install NetCDF4 (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libnetcdf-dev
      - name: Install NetCDF4 (macOS)
        if: matrix.os == 'macos-latest'
        uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: netcdf
          cache: yes
      - name: Install raven-hydro
        run: |
          python -m pip install --editable .
      - name: Test
        run: |
          python -c "import raven_hydro; print(raven_hydro.__version__)"
          raven